### ISSUE TITLE
Add disallowedClasses

### ISSUE THREAD

**Issue by javaDeveloperKid** [spaze/phpstan-disallowed-calls#112]
From docs we know that `5. disallowedNamespaces - for usages of classes from a namespace`. However I need to disallow a single class usage. I could list the constructor method and all the named constructors in disallowedMethodCalls and disallowedStaticCalls but this is to much overhead than just to disallow a class. I tried the disallowedNamespaces parameter but used a FQCN instead of namespace and it worked but I don't know if this is just a coincidence or this parameters works with classes as well (if so then I would just update the docs to mention that and we can close this issue).

Thank you.

**Comment by spaze** [comment]
Hey, you can disallow a class using `disallowedNamespaces` exactly as you've done so and as far as I can tell it's not a coincidence :-) But you're right it's not very straightforward, I'll add `disallowedClasses` config alias and some documentation.

**Comment by spaze** [comment]
Now released as [2.5.0](https://github.com/spaze/phpstan-disallowed-calls/pull/115). Thanks for the idea and let me know if it's now more clear.
