### ISSUE TITLE
disable_functions and disable_classes in php.ini

### ISSUE THREAD

**Issue by staabm** [spaze/phpstan-disallowed-calls#136]
I think it would be helpful to error on calls to functions/usages of classes which are configured to be disabled via php.ini

https://www.php.net/manual/en/ini.core.php#ini.disable-functions

https://www.php.net/manual/en/ini.core.php#ini.disable-classes

Wdyt?

**Comment by spaze** [comment]
Thanks, that sounds good but I think it would create a configuration that would depend on the environment.

For example the FPM php.ini (the "app config") might be different than the CLI php.ini (the "tests config"), and the production php.ini might be different than the CI php.ini. This might result in different functions/classes to be flagged in different environments.

Sort of a config generator, that would read the php.ini config and dump a .neon config to be included in the main config would be nice though I think creating the file manually is very easily done manually.

However I like the idea, and personally I have my disabled_functions in my disabled calls config. I'll think about it for a sec and if nothing else, I'd add a note to the readme file to create a config that would disallow disabled functions/classes.

**Comment by spaze** [comment]
I have added a simple config generator and a README note, thanks for the idea!
