### ISSUE TITLE
Rename branch to `main`

### ISSUE THREAD

**Issue by ruudk** [spaze/phpstan-disallowed-calls#160]
It's very easy and risk free. Go to https://github.com/spaze/phpstan-disallowed-calls/branches and click the edit icon next to the `master` branch.

**Comment by spaze** [comment]
Thanks, I'm aware this can be done and how and indeed wanted to do it for quite some time already but wasn't sure if any "tree/master" web links would be correctly redirected as I haven't seen that particular info published anywhere. Tried that on a different repository and seems that links are correctly redirected so I'll go ahead and rename the branch sooner or later.

**Comment by spaze** [comment]
`master` branch renamed to `main`. Users should see this notice:
![chrome_2023-01-09_21-35-09](https://user-images.githubusercontent.com/1966648/211402992-fc0eba0d-88d5-4e21-b29e-298ee2cc1acd.png)

Copy/paste:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
