### ISSUE TITLE
Add support for disallowing conditions on attributes

### ISSUE THREAD

**Issue by ruudk** [spaze/phpstan-disallowed-calls#179]
I don't have time to contribute the code myself ATM, but just posting this here in case somebody is looking for another great addition to this library: disallowing certain conditions on attributes.

I'm looking for a rule that requires people to set the repositoryClass on a `Doctrine\ORM\Mapping\Entity` attribute.

So when somebody adds `#[Entity]` without specifying the `repositoryClass` it should say: `You should define repositoryClass on Entity`.

- https://github.com/phpstan/phpstan/discussions/9122

**Comment by spaze** [comment]
My idea is to have attribute params should be configurable like any other params.

However useful this seems, I don't currently have a use for such rule. But let's see if anyone else has. Or let's see if I'll be able to finish my sponsorship setup so you could sponsor a release for example.

**Comment by spaze** [comment]
I have released this in [2.13.0](https://github.com/spaze/phpstan-disallowed-calls/releases/tag/v2.13.0) now. Let me know if it works for you and feel free to [buy me a 🍺 or a ☕](https://github.com/sponsors/spaze) if this would save you some non-trivial time 😊

**Comment by ruudk** [comment]
Thanks @spaze. I sponsored you a few good beers, cheers 🍻

**Comment by spaze** [comment]
Thanks @ruudk! 🍻
