### ISSUE TITLE
Allow rule for specific file patterns

### ISSUE THREAD

**Issue by zeleznypa** [spaze/phpstan-disallowed-calls#2]
For example, I want to disallow call `file_get_contents` and replace them with `Nette\Utils\FileSystem::read()`  everywhere exept the PhpUnit test files...

**Comment by spaze** [comment]
Thanks. Can you ignore the error message thrown for those test files with PHPStan's [`ignoreErrors`](https://github.com/phpstan/phpstan/blob/master/README.md#ignore-error-messages-with-regular-expressions)? Supports regexp, wildcards, [counts](https://github.com/phpstan/phpstan/pull/2777).

**Comment by zeleznypa** [comment]
I have prepared a universal list of suggestions for all of my codes that is situated in a separate project, that is required via composer.

the `ignoreErrors` directive is great for project-specific definition but can't be used universal way like this list, because it throws an error, when the situation does not happen.

**Comment by spaze** [comment]
I've added support for `allowIn` in #3, let me know it it works for you (it does for me).
