### ISSUE TITLE
Add PHPCS sniffs

### ISSUE THREAD

**Issue by spaze** [spaze/phpstan-disallowed-calls#22]
Maybe this should have a code sniffer in place.

#21 tried to add PHPCS with PSR-2 which is now [deprecated](https://www.php-fig.org/psr/psr-2/) but I think an up-to-date sniffs should be used in a lib targetting PHP 7.1+, like PSR-12 or Slevomat.

No code changes should be made when the sniffer is introduced, we'll need see how bad it is first :)

The author of #21 didn't want to finish what he has started so this issue is free to grab.

**Comment by szepeviktor** [comment]
> The author of #21

That is me.

**Comment by szepeviktor** [comment]
I suggest you to publish `spaze/coding-standard`
e.g. https://github.com/ramsey/coding-standard
