### ISSUE TITLE
No tests for `disallowedAttributes`

### ISSUE THREAD

**Issue by ruudk** [spaze/phpstan-disallowed-calls#239]
It seems that this is not tested, at all. Or am I missing something?

**Comment by ruudk** [comment]
Luckily, it _is_ tested. It just doesn't use `disallowedAttributes` anywhere in the `tests` folder.

**Comment by spaze** [comment]
Yeah, tested in these tests:
- `\Spaze\PHPStan\Rules\Disallowed\Usages\AttributeUsagesAllowInPathTest`
- `\Spaze\PHPStan\Rules\Disallowed\Usages\AttributeUsagesAllowParamsInAllowedTest`
- `\Spaze\PHPStan\Rules\Disallowed\Usages\AttributeUsagesTest`
