### ISSUE TITLE
ShouldNotHappenException in NonObjectTypeTrait when analyzing one of the classes

### ISSUE THREAD

**Issue by stanislau93** [spaze/phpstan-disallowed-calls#42]
Hello everyone,

Just tried out your nice tool on one of our projects and in one of the files I get the following error:

Stack trace:
```
#0 /app/vendor/spaze/phpstan-disallowed-calls/src/ClassConstantUsages.php(73): PHPStan\Type\StringType->getConstant('STEP_NAME')
#1 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(70): Spaze\PHPStan\Rules\Disallowed\ClassConstantUsages->processNode(Object(PhpParser\Node\Expr\ClassConstFetch), Object(PHPStan\Analyser\MutatingScope))
#2 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(91): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\ClassConstFetch), Object(PHPStan\Analyser\MutatingScope))
#3 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(389): PHPStan\Node\ClassStatementsGatherer->__invoke(Object(PhpParser\Node\Expr\ClassConstFetch), Object(PHPStan\Analyser\MutatingScope))
#4 phar:///app/vendor/phpstan/phpst in phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Type/Traits/NonObjectTypeTrait.php on line 47
```

It breaks when analyzing a class that calls the STEP_NAME constant. The constant with this name is defined in multiple other classes.

Please let me know if you need more details.

**Comment by stanislau93** [comment]
UPDATE

I traced it down to a certain use case
the error appears when the constant is addressed via a variable like this

$something::STEP_NAME

**Comment by spaze** [comment]
Hi @stanislau93. Thanks for the report. `$variable::CONSTANT` is certainly supported when defined on a class:

https://github.com/spaze/phpstan-disallowed-calls/blob/5b88c57c9d84b594d4a831513cd1d9a2fd867308/tests/src/disallowed/constantUsages.php#L18

And now also tested where `$var` is a string or an object: c0195f0db4aad178bffa743c5c8d58cb06efa485

Where's the `STEP_NAME` constant defined and how it's used?

**Comment by stanislau93** [comment]
Hello @spaze,

Thank you for the swift response

we use this constant in a static method to create a value object 
    
public function __construct($name)
    {
        $this->name = $name;
        $this->type = static::TYPE_NORMAL;
    }

    /**
     * @param string $name
     *
     * @return Step
     */
    public static function create($name)
    {
        return new static($name);
    }

It is defined in an abstract class as a public const and later redefined in two classes that extend from it

**Comment by stanislau93** [comment]
Update:

maybe you'll reproduce it after feeding a classname to a function like this - this was actually our use case.

    private function foo(string $myclass = MyClass::class)
    {
          $this->bar->baz($myclass::STEP_NAME);
    }

As I've mentioned before - there are multiple classes that  redefine this constant 

For now we've built a workaround to avoid this issue which seems to work:

    private function foo(string $myclass = MyClass::class, string $stepName = MyClass::STEP_NAME)
    {
...
          $this->bar->baz($myclass::STEP_NAME);
   ...
 }

**Comment by spaze** [comment]
Thanks. I now know where the issue it but I don't know how to fix it properly. I've only made some changes so that PHPStan is not crashing. You'll see errors like `Cannot access constant COOKIE on string` (or `Cannot access constant COOKIE on class-string` if you define the variable as [`class-string`](https://phpstan.org/writing-php-code/phpdoc-types#class-string)) which you need to add to `ignoreErrors` in your `phpstan.neon` config file.

Less than ideal but I think still better than crashes. I'll release the fix in a few days unless I get some better idea (don't hold your breath).

**Comment by spaze** [comment]
1.2.0 which contains the crash fix has been released.

**Comment by stanislau93** [comment]
Great, many thanks for your help!
