### ISSUE TITLE
Disallow any usage of namespace in code

### ISSUE THREAD

**Issue by ruudk** [spaze/phpstan-disallowed-calls#50]
Can this library also be used to clock the usage of certain namespaces?

For example, I want to forbid importing, static calls, instantiation, method calls on `Carbon` namespace and suggest `Chronos` (just an example).

**Comment by spaze** [comment]
Currently, this is not possible. But it may be useful so leaving the issue open for anyone who'd like to implement it.

Guess it would be nice to have each disallowed namespace list what's actually disallowed:
- `use` imports
- `Static::call()`
- `new Namespace`
- `Namespace\Class::CONST`
- `$this->namespacedObj->call`)
-  or `*` for all things

**Comment by spaze** [comment]
Closed by #51
