### ISSUE TITLE
Make it a PHPStan Extension

### ISSUE THREAD

**Issue by szepeviktor** [spaze/phpstan-disallowed-calls#6]
`    "type": "phpstan-extension",`

Why don't you make it an extension with sane defaults and easy configuration?

e.g. https://github.com/ekino/phpstan-banned-code/blob/master/composer.json#L3

**Comment by spaze** [comment]
Thanks, I've learned about `"type": "phpstan-extension"` only earlier today, will add it.

I'm not sure what the defaults should be as every project is different but I'm open to suggestions. Also, what would you think an easy configuration should look like?

**Comment by szepeviktor** [comment]
> I'm not sure what the defaults should be

In my fantasy/perfectionist world there are

https://github.com/szepeviktor/debian-server-tools/blob/f69faf72eac5c96f32721e35554cf321f49097e9/webserver/laravel/phpcs.xml#L21-L28

Here is a list of really bad ideas.

- extract
- eval
- print and print_r
- var_dump

**Comment by szepeviktor** [comment]
> what would you think an easy configuration should look like?

That package has a relatively short NEON config: types & functions.

https://github.com/ekino/phpstan-banned-code#advanced-usage

**Comment by spaze** [comment]
I don't like this part of the config either:
```
    class: Spaze\PHPStan\Rules\Disallowed\MethodCalls
        tags:
            - phpstan.rules.rule
        arguments:
```
I'll think if this can be removed somehow. The `DisallowedHelper` will probably be removed from the manual config in #9. The rest of the config will stay (this extension also offers recommendations and can exclude paths, calls).

**Comment by szepeviktor** [comment]
> I'll think if this can be removed somehow.

It is very simple.

1. extension stuff goes into the standard `extension.neon`
1. user stuff goes into the user's config in `parameters:`

**Comment by spaze** [comment]
Thanks, that's how extensions work indeed.
