### ISSUE TITLE
Disabling Else / Elseif

### ISSUE THREAD

**Issue by JBx0** [spaze/phpstan-disallowed-calls#68]
Hey hey,
I would love to enable else/elseif in my codebase.

How would one go and do that, I tried all kinds of wildcard strings whitespace etc etc with your package but it didn't pick up any else & elseifs

I managed to detect elseifs with the banned code extension like this:
```
            -
                type: Stmt_ElseIf
                functions: null
```

Tried it with: 
```
 disallowedMethodCalls:
            -
                method: 'PhpParser\Node\Stm\Else::__construct'
                message: 'use earlier return types and/or smaller methods'
            -
                method: 'PhpParser\Node\Stm\ElseIf::___construct'
                message: 'use earlier return types and/or smaller methods'
                
    disallowedFunctionCalls:
        -
            function: 'else*(*)*'
            message: 'use logger instead'
        -
            function: 'ElseIf*'
            message: 'use logger instead'
        -
            function: 'elseif*'
            message: 'use logger instead'
        -
            function: 'elseIf '
            message: 'use logger instead'
        -
            function: 'ElseIf()'
            message: 'use logger instead'
        -
            function: 'ElseIf ()'
            message: 'use logger instead'                
```

**Comment by spaze** [comment]
I'm generally open for PRs and welcome them but in this case I think the PR would be too big for a feature that would be rarely used. Disallowing only `else`s and `elseif`s alone wouldn't make much sense so probably all the control structures would need to be supported. And there's quite a few of them https://www.php.net/manual/en/language.control-structures.php 😜

I'd say you'd be better off with a custom PHPStan extension, if you're not willing to use the banned code extension. Building a custom extension might be easier than it seems. For example look at the following class
https://github.com/spaze/phpstan-disallowed-calls/blob/master/src/FunctionCalls.php
`getNodeType()` would need to return `ElseIf_`  and `processNode` would `return ['nope']`.

Then you need to register the extension, similar (a bit easier) to

https://github.com/spaze/phpstan-disallowed-calls/blob/b99318e15a968c58148cc69940f78412fa421efe/extension.neon#L81-84

Let me know if you need help.

**Comment by spaze** [comment]
Hey @JBx0, now as the extension has matured a bit, I was wondering whether adding support for `if` and `else` and more language constructs would be easier than before and there's only one way to find out 😀 But I was wondering whether it would still be useful for you if I add the support?

**Comment by spaze** [comment]
Added basic support to disallow control structures in #257.
