### ISSUE TITLE
Retire Travis CI and switch to GitHub actions

### ISSUE THREAD

**Issue by spaze** [spaze/phpstan-disallowed-calls#8]
Use `composer update` instead of `composer install` because Composer 2 throws a warning, see the discussion in #7.

**Comment by szepeviktor** [comment]
I miss him right now!

![Travis](https://travis-ci.org/images/logos/TravisCI-Mascot-4.svg)

**Comment by szepeviktor** [comment]
You may start with https://github.com/ergebnis/php-library-template/blob/main/.github/workflows/integrate.yaml

**Comment by spaze** [comment]
Nah, that's overkill.

**Comment by szepeviktor** [comment]
I've realized that _basic_ is not really basic.

I introduce these 3 basic tests in all projects.

1. syntax check
1. coding standard
1. static analysis

BTW It is a shame not to run static analysis on a PHPStan extension...
