### ISSUE TITLE
Case insensitive function calls

### ISSUE THREAD

**Issue by lulco** [spaze/phpstan-disallowed-calls#93]
I'm writing function `print_r()` very often as `print_R()`. Probably because of holding shift for `_` and also `(`. Everything works because function names are case-insensitive, but this extension can't identify it as disallowed.

Failing test case added [here](https://github.com/spaze/phpstan-disallowed-calls/pull/92).

**Comment by spaze** [comment]
Fair point, thanks! Fixed and released in [2.1.0](https://github.com/spaze/phpstan-disallowed-calls/releases/tag/v2.1.0). You can also check out [strict rules](https://github.com/phpstan/phpstan-strict-rules) to find case-mismatched calls, see [example](https://phpstan.org/r/408f8f14-8bab-4fc9-b9cf-11eee6fc7984).
