### ISSUE TITLE
Disallowing method calls but allowing usage within a trait does not work as expected

### ISSUE THREAD

**Issue by ruudk** [spaze/phpstan-disallowed-calls#99]
_I wanted to create a failing test PR but it didn't work, therefore this issue instead._

I'm trying to disallow calls to `AbstractController::getUser()` while encouraging people to use my special `UserTrait::getUserOrThrow()` wrapper that in turn uses `AbstractController::getUser()`.

It turns out that it's not possible currently. 

This is my configuration:
```neon
parameters:
    disallowedMethodCalls:
        -
            method: 'Symfony\Bundle\FrameworkBundle\Controller\AbstractController::getUser()'
            message: 'import UserTrait and use getUserOrThrow() instead.'
            allowIn:
                - **/src/UserTrait.php
```

This is the code from Symfony that I want to disallow:
```php
namespace Symfony\Bundle\FrameworkBundle\Controller;

abstract class AbstractController implements ServiceSubscriberInterface
{
    protected function getUser()
    {
        // returns the user
    }
}
```

My trait, that people should use instead:
```php
namespace App;

trait UserTrait
{
    /**
     * @throws UserNotLoggedInException
     */
    public function getUserOrThrow() : User
    {
        $user = $this->getUser();

        if ($user instanceof User === false) {
            throw UserNotLoggedInException::create();
        }

        return $user;
    }
}
```

An example of the usage of the `UserTrait`:
```php
namespace App;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

final class MyController extends AbstractController
{
    use UserTrait;

    public function myAction()
    {
        $user = $this->getUserOrThrow();
    }
}
```

But this results in the following error:
```
 ------ -----------------------------------------------------------------------------------------------------------------------------------------------------------------
  Line  UserTrait.php (in context of class MyController)
 ------ -----------------------------------------------------------------------------------------------------------------------------------------------------------------
  10     Calling Symfony\Bundle\FrameworkBundle\Controller\AbstractController::getUser() (as MyController::getUser()) is forbidden, import UserTrait and use getUserOrThrow() instead.
         ✏️  phpstorm://open?file=/Volumes/CS/www/website/src/UserTrait.php&line=22
```

**Comment by spaze** [comment]
First things first, thanks for the issue and for the research (and for trying to write a test) and sorry it took this long.

Second, oh my god wow! 😅 I can confirm it's not possible to write a test right now, seems like for some reason PHPStan thinks, when running a test, that the call is not in a trait (`$scope->getTraitReflection()` returns `null`), and I tried.

I've fixed the issue now, will release shortly. Once released, can you please confirm it works for you? Thanks.

**Comment by spaze** [comment]
Released now in [2.2.0](https://github.com/spaze/phpstan-disallowed-calls/releases/tag/v2.2.0).

**Comment by ruudk** [comment]
It worked! Amazing, thank you so much!

**Comment by spaze** [comment]
![yes-sweet](https://user-images.githubusercontent.com/1966648/148470176-3fd25b52-f502-4bf1-817f-7015b266114f.gif)
